name: Deploy MultiDocker

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t gokulcs4u/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true gokulcs4u/react-test npm run test -- --coverage

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          region: ap-south-1
          application_name: Docker-React
          environment_name: Docker-react-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-092737449886
          version_label: 12346
          deployment_package: deploy.zip
