name: Deploy MultiDocker

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t gokulcs4u/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true gokulcs4u/react-test npm run test -- --coverage
